### ISSUE TITLE
Patch for /trunk/tv_grab_file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Rigolo/tv-grab-file#1]
```
change printed output to "..grab.." from "...graf..."
```

Original issue reported on code.google.com by `Intlvel...@gmail.com` on 2 Jul 2012 at 1:36

Attachments:
- [tv_grab_file.patch](https://storage.googleapis.com/google-code-attachments/tv-grab-file/issue-1/comment-0/tv_grab_file.patch)

**Comment by Rigolo** [comment]
solved in first change on github
